[0.000000] (-) TimerEvent: {}
[0.000631] (controller) JobQueued: {'identifier': 'controller', 'dependencies': OrderedDict()}
[0.000714] (messages) JobQueued: {'identifier': 'messages', 'dependencies': OrderedDict()}
[0.000758] (controller) JobStarted: {'identifier': 'controller'}
[0.062616] (messages) JobStarted: {'identifier': 'messages'}
[0.091346] (-) TimerEvent: {}
[0.197127] (-) TimerEvent: {}
[0.297674] (-) TimerEvent: {}
[0.398073] (-) TimerEvent: {}
[0.498439] (-) TimerEvent: {}
[0.598805] (-) TimerEvent: {}
[0.699194] (-) TimerEvent: {}
[0.799625] (-) TimerEvent: {}
[0.900206] (-) TimerEvent: {}
[1.000592] (-) TimerEvent: {}
[1.101290] (-) TimerEvent: {}
[1.202004] (-) TimerEvent: {}
[1.302442] (-) TimerEvent: {}
[1.358241] (controller) StderrLine: {'line': b'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__\n    rc = await self.task(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__\n    return await task_method(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 51, in build\n    setup_py_data = get_setup_data(self.context.pkg, env)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/__init__.py", line 20, in get_setup_data\n    return dict(pkg.metadata[key](env))\n  File "/usr/lib/python3/dist-packages/colcon_ros/package_identification/ros.py", line 129, in getter\n    return get_setup_information(\n  File "/usr/lib/python3/dist-packages/colcon_python_setup_py/package_identification/python_setup_py.py", line 241, in get_setup_information\n    _setup_information_cache[hashable_env] = _get_setup_information(\n  File "/usr/lib/python3/dist-packages/colcon_python_setup_py/package_identification/python_setup_py.py", line 281, in _get_setup_information\n    result = subprocess.run(\n  File "/usr/lib/python3.8/subprocess.py", line 516, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'[\'/usr/bin/python3\', \'-c\', "import sys;from setuptools.extern.packaging.specifiers import SpecifierSet;from distutils.core import run_setup;dist = run_setup(    \'setup.py\', script_args=(\'--dry-run\',), stop_after=\'config\');skip_keys = (\'cmdclass\', \'distclass\', \'ext_modules\', \'metadata\');data = {    key: value for key, value in dist.__dict__.items()     if (        not key.startswith(\'_\') and         not callable(value) and         key not in skip_keys and         key not in dist.display_option_names    )};data[\'metadata\'] = {    k: v for k, v in dist.metadata.__dict__.items()     if k not in (\'license_files\', \'provides_extras\')};sys.stdout.buffer.write(repr(data).encode(\'utf-8\'))"]\' returned non-zero exit status 1.\n'}
[1.359422] (controller) JobEnded: {'identifier': 'controller', 'rc': 1}
[1.362755] (messages) JobEnded: {'identifier': 'messages', 'rc': 'SIGINT'}
[1.370071] (-) EventReactorShutdown: {}
